export default [
  {
    month: 'June',
    photos: [
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
      require('./statics/photo4.png'),
      require('./statics/photo1.png'),
      require('./statics/photo4.png'),
      require('./statics/photo2.png'),
      require('./statics/photo2.png'),
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
      require('./statics/photo3.png'),
      require('./statics/photo1.png'),
      require('./statics/photo3.png'),
      require('./statics/photo4.png'),
      require('./statics/photo2.png'),
      require('./statics/photo1.png'),
      require('./statics/photo4.png'),
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
    ]
  },
  {
    month: 'April',
    photos: [
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
      require('./statics/photo4.png'),
      require('./statics/photo1.png'),
      require('./statics/photo4.png'),
      require('./statics/photo2.png'),
      require('./statics/photo2.png'),
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
      require('./statics/photo3.png'),
      require('./statics/photo1.png'),
      require('./statics/photo3.png'),
      require('./statics/photo4.png'),
      require('./statics/photo2.png'),
      require('./statics/photo1.png'),
      require('./statics/photo4.png'),
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
    ]
  },
  {
    month: 'March',
    photos: [
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
      require('./statics/photo4.png'),
      require('./statics/photo1.png'),
      require('./statics/photo4.png'),
      require('./statics/photo2.png'),
      require('./statics/photo2.png'),
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
      require('./statics/photo3.png'),
      require('./statics/photo1.png'),
      require('./statics/photo3.png'),
      require('./statics/photo4.png'),
      require('./statics/photo2.png'),
      require('./statics/photo1.png'),
      require('./statics/photo4.png'),
      require('./statics/photo1.png'),
      require('./statics/photo2.png'),
    ]
  }
]